package org.strandz.data.wombatrescue.objects.cayenne.auto;

import org.apache.cayenne.CayenneDataObject;
import org.strandz.data.wombatrescue.objects.cayenne.DayInWeek;
import org.strandz.data.wombatrescue.objects.cayenne.WhichShift;
import org.strandz.data.wombatrescue.objects.cayenne.Worker;

/**
 * Class _BuddyManager was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _BuddyManager extends CayenneDataObject {

    public static final String DAYINWEEK_PKID_PROPERTY = "dayinweekPkid";
    public static final String JDOCLASS_PROPERTY = "jdoclass";
    public static final String JDOVERSION_PROPERTY = "jdoversion";
    public static final String WHICHSHIFT_PKID_PROPERTY = "whichshiftPkid";
    public static final String WORKER_JDOID_PROPERTY = "workerJdoid";
    public static final String ACTUAL_DAY_IN_WEEK_PROPERTY = "actualDayInWeek";
    public static final String ACTUAL_WHICH_SHIFT_PROPERTY = "actualWhichShift";
    public static final String ACTUAL_WORKER_PROPERTY = "actualWorker";

    public static final String JDOID_PK_COLUMN = "JDOID";

    public void setDayinweekPkid(Integer dayinweekPkid) {
        writeProperty("dayinweekPkid", dayinweekPkid);
    }
    public Integer getDayinweekPkid() {
        return (Integer)readProperty("dayinweekPkid");
    }

    public void setJdoclass(String jdoclass) {
        writeProperty("jdoclass", jdoclass);
    }
    public String getJdoclass() {
        return (String)readProperty("jdoclass");
    }

    public void setJdoversion(Integer jdoversion) {
        writeProperty("jdoversion", jdoversion);
    }
    public Integer getJdoversion() {
        return (Integer)readProperty("jdoversion");
    }

    public void setWhichshiftPkid(Integer whichshiftPkid) {
        writeProperty("whichshiftPkid", whichshiftPkid);
    }
    public Integer getWhichshiftPkid() {
        return (Integer)readProperty("whichshiftPkid");
    }

    public void setWorkerJdoid(Long workerJdoid) {
        writeProperty("workerJdoid", workerJdoid);
    }
    public Long getWorkerJdoid() {
        return (Long)readProperty("workerJdoid");
    }

    public void setActualDayInWeek(DayInWeek actualDayInWeek) {
        setToOneTarget("actualDayInWeek", actualDayInWeek, true);
    }

    public DayInWeek getActualDayInWeek() {
        return (DayInWeek)readProperty("actualDayInWeek");
    }


    public void setActualWhichShift(WhichShift actualWhichShift) {
        setToOneTarget("actualWhichShift", actualWhichShift, true);
    }

    public WhichShift getActualWhichShift() {
        return (WhichShift)readProperty("actualWhichShift");
    }


    public void setActualWorker(Worker actualWorker) {
        setToOneTarget("actualWorker", actualWorker, true);
    }

    public Worker getActualWorker() {
        return (Worker)readProperty("actualWorker");
    }


}
