package org.strandz.data.wombatrescue.objects.cayenne.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.strandz.data.wombatrescue.objects.cayenne.BuddyManager;
import org.strandz.data.wombatrescue.objects.cayenne.Flexibility;
import org.strandz.data.wombatrescue.objects.cayenne.RosterSlot;
import org.strandz.data.wombatrescue.objects.cayenne.Seniority;
import org.strandz.data.wombatrescue.objects.cayenne.Sex;
import org.strandz.data.wombatrescue.objects.cayenne.WhichShift;
import org.strandz.data.wombatrescue.objects.cayenne.Worker;

/**
 * Class _Worker was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Worker extends CayenneDataObject {

    public static final String AWAY1END_PROPERTY = "away1End";
    public static final String AWAY1START_PROPERTY = "away1Start";
    public static final String AWAY2END_PROPERTY = "away2End";
    public static final String AWAY2START_PROPERTY = "away2Start";
    public static final String BIRTHDAY_PROPERTY = "birthday";
    public static final String CHRISTIAN_NAME_PROPERTY = "christianName";
    public static final String COMMENTS_PROPERTY = "comments";
    public static final String CONTACT_NAME_PROPERTY = "contactName";
    public static final String DUMMY_PROPERTY = "dummy";
    public static final String EMAIL1_PROPERTY = "email1";
    public static final String EMAIL2_PROPERTY = "email2";
    public static final String GROUP_CONTACT_PERSON_PROPERTY = "groupContactPerson";
    public static final String GROUP_NAME_PROPERTY = "groupName";
    public static final String HOME_PHONE_PROPERTY = "homePhone";
    public static final String JDOCLASS_PROPERTY = "jdoclass";
    public static final String JDOVERSION_PROPERTY = "jdoversion";
    public static final String MOBILE_PHONE_PROPERTY = "mobilePhone";
    public static final String POSTCODE_PROPERTY = "postcode";
    public static final String STREET_PROPERTY = "street";
    public static final String SUBURB_PROPERTY = "suburb";
    public static final String SURNAME_PROPERTY = "surname";
    public static final String UNKNOWN_PROPERTY = "unknown";
    public static final String WORK_PHONE_PROPERTY = "workPhone";
    public static final String ACTUAL_BELONGS_TO_GROUP_PROPERTY = "actualBelongsToGroup";
    public static final String ACTUAL_FLEXIBILITY_PROPERTY = "actualFlexibility";
    public static final String ACTUAL_SENIORITY_PROPERTY = "actualSeniority";
    public static final String ACTUAL_SEX_PROPERTY = "actualSex";
    public static final String ACTUAL_SHIFT_PREFERENCE_PROPERTY = "actualShiftPreference";
    public static final String BUDDY_MANAGER_PROPERTY = "buddyManager";
    public static final String ROSTER_SLOTS_PROPERTY = "rosterSlots";
    public static final String WORKERS_IN_GROUP_PROPERTY = "workersInGroup";

    public static final String JDOID_PK_COLUMN = "JDOID";

    public void setAway1End(Date away1End) {
        writeProperty("away1End", away1End);
    }
    public Date getAway1End() {
        return (Date)readProperty("away1End");
    }

    public void setAway1Start(Date away1Start) {
        writeProperty("away1Start", away1Start);
    }
    public Date getAway1Start() {
        return (Date)readProperty("away1Start");
    }

    public void setAway2End(Date away2End) {
        writeProperty("away2End", away2End);
    }
    public Date getAway2End() {
        return (Date)readProperty("away2End");
    }

    public void setAway2Start(Date away2Start) {
        writeProperty("away2Start", away2Start);
    }
    public Date getAway2Start() {
        return (Date)readProperty("away2Start");
    }

    public void setBirthday(Date birthday) {
        writeProperty("birthday", birthday);
    }
    public Date getBirthday() {
        return (Date)readProperty("birthday");
    }

    public void setChristianName(String christianName) {
        writeProperty("christianName", christianName);
    }
    public String getChristianName() {
        return (String)readProperty("christianName");
    }

    public void setComments(String comments) {
        writeProperty("comments", comments);
    }
    public String getComments() {
        return (String)readProperty("comments");
    }

    public void setContactName(String contactName) {
        writeProperty("contactName", contactName);
    }
    public String getContactName() {
        return (String)readProperty("contactName");
    }

    public void setDummy(boolean dummy) {
        writeProperty("dummy", dummy);
    }
	public boolean isDummy() {
        Boolean value = (Boolean)readProperty("dummy");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setEmail1(String email1) {
        writeProperty("email1", email1);
    }
    public String getEmail1() {
        return (String)readProperty("email1");
    }

    public void setEmail2(String email2) {
        writeProperty("email2", email2);
    }
    public String getEmail2() {
        return (String)readProperty("email2");
    }

    public void setGroupContactPerson(boolean groupContactPerson) {
        writeProperty("groupContactPerson", groupContactPerson);
    }
	public boolean isGroupContactPerson() {
        Boolean value = (Boolean)readProperty("groupContactPerson");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setGroupName(String groupName) {
        writeProperty("groupName", groupName);
    }
    public String getGroupName() {
        return (String)readProperty("groupName");
    }

    public void setHomePhone(String homePhone) {
        writeProperty("homePhone", homePhone);
    }
    public String getHomePhone() {
        return (String)readProperty("homePhone");
    }

    public void setJdoclass(String jdoclass) {
        writeProperty("jdoclass", jdoclass);
    }
    public String getJdoclass() {
        return (String)readProperty("jdoclass");
    }

    public void setJdoversion(Integer jdoversion) {
        writeProperty("jdoversion", jdoversion);
    }
    public Integer getJdoversion() {
        return (Integer)readProperty("jdoversion");
    }

    public void setMobilePhone(String mobilePhone) {
        writeProperty("mobilePhone", mobilePhone);
    }
    public String getMobilePhone() {
        return (String)readProperty("mobilePhone");
    }

    public void setPostcode(String postcode) {
        writeProperty("postcode", postcode);
    }
    public String getPostcode() {
        return (String)readProperty("postcode");
    }

    public void setStreet(String street) {
        writeProperty("street", street);
    }
    public String getStreet() {
        return (String)readProperty("street");
    }

    public void setSuburb(String suburb) {
        writeProperty("suburb", suburb);
    }
    public String getSuburb() {
        return (String)readProperty("suburb");
    }

    public void setSurname(String surname) {
        writeProperty("surname", surname);
    }
    public String getSurname() {
        return (String)readProperty("surname");
    }

    public void setUnknown(boolean unknown) {
        writeProperty("unknown", unknown);
    }
	public boolean isUnknown() {
        Boolean value = (Boolean)readProperty("unknown");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setWorkPhone(String workPhone) {
        writeProperty("workPhone", workPhone);
    }
    public String getWorkPhone() {
        return (String)readProperty("workPhone");
    }

    public void setActualBelongsToGroup(Worker actualBelongsToGroup) {
        setToOneTarget("actualBelongsToGroup", actualBelongsToGroup, true);
    }

    public Worker getActualBelongsToGroup() {
        return (Worker)readProperty("actualBelongsToGroup");
    }


    public void setActualFlexibility(Flexibility actualFlexibility) {
        setToOneTarget("actualFlexibility", actualFlexibility, true);
    }

    public Flexibility getActualFlexibility() {
        return (Flexibility)readProperty("actualFlexibility");
    }


    public void setActualSeniority(Seniority actualSeniority) {
        setToOneTarget("actualSeniority", actualSeniority, true);
    }

    public Seniority getActualSeniority() {
        return (Seniority)readProperty("actualSeniority");
    }


    public void setActualSex(Sex actualSex) {
        setToOneTarget("actualSex", actualSex, true);
    }

    public Sex getActualSex() {
        return (Sex)readProperty("actualSex");
    }


    public void setActualShiftPreference(WhichShift actualShiftPreference) {
        setToOneTarget("actualShiftPreference", actualShiftPreference, true);
    }

    public WhichShift getActualShiftPreference() {
        return (WhichShift)readProperty("actualShiftPreference");
    }


    public void addToBuddyManager(BuddyManager obj) {
        addToManyTarget("buddyManager", obj, true);
    }
    public void removeFromBuddyManager(BuddyManager obj) {
        removeToManyTarget("buddyManager", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<BuddyManager> getBuddyManager() {
        return (List<BuddyManager>)readProperty("buddyManager");
    }


    public void addToRosterSlots(RosterSlot obj) {
        addToManyTarget("rosterSlots", obj, true);
    }
    public void removeFromRosterSlots(RosterSlot obj) {
        removeToManyTarget("rosterSlots", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<RosterSlot> getRosterSlots() {
        return (List<RosterSlot>)readProperty("rosterSlots");
    }


    public void addToWorkersInGroup(Worker obj) {
        addToManyTarget("workersInGroup", obj, true);
    }
    public void removeFromWorkersInGroup(Worker obj) {
        removeToManyTarget("workersInGroup", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Worker> getWorkersInGroup() {
        return (List<Worker>)readProperty("workersInGroup");
    }


}
