<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE helpset PUBLIC "-//Sun Microsystems Inc.//DTD JavaHelp HelpSet Version 1.0//EN" "http://java.sun.com/products/javahelp/helpset_1_0.dtd"><!--generated by JHelpDev Version: 0.3, 1 June 2005, see jhelpdev.sourceforge.net-->

<helpset version="1.0">
 <title>
Wombat Rescue Help 
 </title>
 <maps>
  <homeID>
top
  </homeID>
  <mapref location="Map.jhm"/>

 </maps>
 <view>
  <name>
TOC
  </name>
  <label>
TOC 
  </label>
  <type>
javax.help.TOCView
  </type>
  <data>
WombatRescueHelpTOC.xml
  </data>
 </view>
</helpset>