package org.strandz.data.gallery.objects.auto;

import java.util.List;

/** Class _Artist was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Artist extends org.apache.cayenne.CayenneDataObject {

    public static final String ARTIST_NAME_PROPERTY = "artistName";
    public static final String DATE_OF_BIRTH_PROPERTY = "dateOfBirth";
    public static final String ARTIST_ARRAY_PROPERTY = "artistArray";
    public static final String PAINTING_ARRAY_PROPERTY = "paintingArray";
    public static final String PAINTINGS_PROPERTY = "paintings";
    public static final String TO_ARTIST_PROPERTY = "toArtist";

    public static final String ARTIST_ID_PK_COLUMN = "ARTIST_ID";

    public void setArtistName(String artistName) {
        writeProperty("artistName", artistName);
    }
    public String getArtistName() {
        return (String)readProperty("artistName");
    }
    
    
    public void setDateOfBirth(java.util.Date dateOfBirth) {
        writeProperty("dateOfBirth", dateOfBirth);
    }
    public java.util.Date getDateOfBirth() {
        return (java.util.Date)readProperty("dateOfBirth");
    }
    
    
    public void addToArtistArray(org.strandz.data.gallery.objects.Artist obj) {
        addToManyTarget("artistArray", obj, true);
    }
    public void removeFromArtistArray(org.strandz.data.gallery.objects.Artist obj) {
        removeToManyTarget("artistArray", obj, true);
    }
    public List getArtistArray() {
        return (List)readProperty("artistArray");
    }
    
    
    public void addToPaintingArray(org.strandz.data.gallery.objects.Painting obj) {
        addToManyTarget("paintingArray", obj, true);
    }
    public void removeFromPaintingArray(org.strandz.data.gallery.objects.Painting obj) {
        removeToManyTarget("paintingArray", obj, true);
    }
    public List getPaintingArray() {
        return (List)readProperty("paintingArray");
    }
    
    
    public void addToPaintings(org.strandz.data.gallery.objects.Painting obj) {
        addToManyTarget("paintings", obj, true);
    }
    public void removeFromPaintings(org.strandz.data.gallery.objects.Painting obj) {
        removeToManyTarget("paintings", obj, true);
    }
    public List getPaintings() {
        return (List)readProperty("paintings");
    }
    
    
    public void setToArtist(org.strandz.data.gallery.objects.Artist toArtist) {
        setToOneTarget("toArtist", toArtist, true);
    }

    public org.strandz.data.gallery.objects.Artist getToArtist() {
        return (org.strandz.data.gallery.objects.Artist)readProperty("toArtist");
    } 
    
    
}
