package org.strandz.data.gallery.objects.auto;

/** Class _Painting was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Painting extends org.apache.cayenne.CayenneDataObject {

    public static final String ESTIMATED_PRICE_PROPERTY = "estimatedPrice";
    public static final String PAINTING_TITLE_PROPERTY = "paintingTitle";
    public static final String ARTIST_PROPERTY = "artist";
    public static final String TO_ARTIST_PROPERTY = "toArtist";
    public static final String TO_GALLERY_PROPERTY = "toGallery";

    public static final String PAINTING_ID_PK_COLUMN = "PAINTING_ID";

    public void setEstimatedPrice(Integer estimatedPrice) {
        writeProperty("estimatedPrice", estimatedPrice);
    }
    public Integer getEstimatedPrice() {
        return (Integer)readProperty("estimatedPrice");
    }
    
    
    public void setPaintingTitle(String paintingTitle) {
        writeProperty("paintingTitle", paintingTitle);
    }
    public String getPaintingTitle() {
        return (String)readProperty("paintingTitle");
    }
    
    
    public void setArtist(org.strandz.data.gallery.objects.Artist artist) {
        setToOneTarget("artist", artist, true);
    }

    public org.strandz.data.gallery.objects.Artist getArtist() {
        return (org.strandz.data.gallery.objects.Artist)readProperty("artist");
    } 
    
    
    public void setToArtist(org.strandz.data.gallery.objects.Artist toArtist) {
        setToOneTarget("toArtist", toArtist, true);
    }

    public org.strandz.data.gallery.objects.Artist getToArtist() {
        return (org.strandz.data.gallery.objects.Artist)readProperty("toArtist");
    } 
    
    
    public void setToGallery(org.strandz.data.gallery.objects.Gallery toGallery) {
        setToOneTarget("toGallery", toGallery, true);
    }

    public org.strandz.data.gallery.objects.Gallery getToGallery() {
        return (org.strandz.data.gallery.objects.Gallery)readProperty("toGallery");
    } 
    
    
}
